### ISSUE TITLE
03 vue_calendar / Vue環境構築 (npm)

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/calendar-demo#6]
##　実装方針
[Vue.jsとLaravelでカレンダーアプリを作成する EP1 - ヴォルクルス神殿](https://volkruss.com/2020/05/21/vue-js%e3%81%a8laravel%e3%81%a7%e3%82%ab%e3%83%ac%e3%83%b3%e3%83%80%e3%83%bc%e3%82%a2%e3%83%97%e3%83%aa%e3%82%92%e4%bd%9c%e6%88%90%e3%81%99%e3%82%8b-ep1/)

**Comment by hasyrails** [comment]
### 参考(php)
``` php
$ npm install
$ npm install -D vue
$ npm run dev
```
### Rails

```
$ npm run dev
npm ERR! missing script: dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shota/.npm/_logs/2020-09-01T12_00_53_085Z-debug.log
```

[npm run dev　エラー（npm ERR! missing script: dev）](https://qiita.com/baby-0105/items/f3e345b0506fb1b52fef)

``` js
{
+  "scripts": {
+    "dev": "webpack --mode development"
+  },
}
```

```
$ npm run dev

> calendar-demo@ dev /Users/shota/calendar-demo
> webpack --mode development

sh: webpack: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! calendar-demo@ dev: `webpack --mode development`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the calendar-demo@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shota/.npm/_logs/2020-09-01T12_02_06_798Z-debug.log

```

[sh: webpack: command not found](https://teratail.com/questions/259246)

```
$ npm install -g webpack
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
/Users/shota/.nvm/versions/node/v12.18.1/bin/webpack -> /Users/shota/.nvm/versions/node/v12.18.1/lib/node_modules/webpack/bin/webpack.js

> fsevents@1.2.13 install /Users/shota/.nvm/versions/node/v12.18.1/lib/node_modules/webpack/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/shota/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/shota/.nvm/versions/node/v12.18.1/bin/node" "/Users/shota/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/shota/.nvm/versions/node/v12.18.1/lib/node_modules/webpack/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v12.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.18.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0

+ webpack@4.44.1
added 350 packages from 211 contributors in 22.084s
```

```
$ npm run dev           

> calendar-demo@ dev /Users/shota/calendar-demo
> webpack --mode development

One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "npm" to install the CLI via "npm install -D".
Do you want to install 'webpack-cli' (yes/no): y
Installing 'webpack-cli' (running 'npm install -D webpack-cli')...
npm WARN webpack-cli@3.3.12 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.

+ webpack-cli@3.3.12
added 185 packages from 127 contributors and audited 186 packages in 12.098s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Error: Cannot find module 'webpack-cli'
Require stack:
- /Users/shota/.nvm/versions/node/v12.18.1/lib/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /Users/shota/.nvm/versions/node/v12.18.1/lib/node_modules/webpack/bin/webpack.js:143:5
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/shota/.nvm/versions/node/v12.18.1/lib/node_modules/webpack/bin/webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! calendar-demo@ dev: `webpack --mode development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the calendar-demo@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shota/.npm/_logs/2020-09-01T12_08_47_830Z-debug.log
```

**Comment by hasyrails** [comment]
npmだとエラーになるのでyarnで進める

[【VueJS+yarn】Vue CLIを使ってvueプロジェクトの作成をする](https://qiita.com/hisayuki/items/8cf2396f122ca6e452ee)

**Comment by hasyrails** [comment]
vue-cliだとRailsのポートで起動できない
```
DONE  Compiled successfully in 3354ms                                                       21:29:04


  App running at:
  - Local:   http://localhost:8081/ 
  - Network: http://192.168.100.103:8081/

  Note that the development build is not optimized.
  To create a production build, run npm run build.
```

**Comment by hasyrails** [comment]
[Vue.jsとRailsでTODOアプリのチュートリアルみたいなものを作ってみた](https://qiita.com/naoki85/items/51a8b0f2cbf949d08b11)

**Comment by hasyrails** [comment]
## rails new の段階からの話らしい
```
rails new todo_sample --webpack=vue
```

**Comment by hasyrails** [comment]
新たに
```
$ rails new vue-calendar-trial --webpack=vue
```
